package com.y9vad9.minesweeper.ui

import com.y9vad9.minesweeper.Difficulty

data class Strings(
    val seedLabel: String,
    val copySeedButton: String,
    val seedCopiedToast: String,
    val newGameButton: String,
    val startButton: String,
    val stopAndStartButton: String,
    val difficultyLabel: String,
    val orPasteSeed: String,
    val seedFormatHint: String,
    val seedFormatError: String,
    val playAgainButton: String,
    val gameWonHeadline: String,
    val gameLostHeadline: String,
    val clearedInPrefix: String,
    val lastedPrefix: String,
    val easyLabel: String,
    val mediumLabel: String,
    val hardLabel: String,

    val gameTab: String,
    val historyTab: String,
    val settingsTab: String,
    val historyHeader: String,
    val historyEmpty: String,
    val historyClear: String,
    val outcomeWon: String,
    val outcomeLost: String,

    val statsHeader: String,
    val statsBestTime: String,
    val statsAverageTime: String,
    val statsAverageWinTime: String,
    val statsAverageLossTime: String,
    val statsWinRate: String,
    val statsTotalGames: String,
    val statsTotalWins: String,
    val statsTotalLosses: String,
    val statsCurrentStreak: String,
    val statsLongestStreak: String,
    val statsThreeBV: String,
    val statsThreeBVPerSecond: String,
    val statsAverageThreeBVPerSecond: String,
    val statsMedianTime: String,
    val statsRecentGames: String,
    val statsBack: String,
    val statsNoData: String,
    val statsWinTimeChartLabel: String,
    val statsChartAllGames: String,
    val statsChartWinsOnly: String,
    val statsChartLossesOnly: String,

    val settingsHeader: String,
    val languageLabel: String,
    val themeLabel: String,
    val themeDark: String,
    val themeLight: String,
    val themeSystem: String,
    val skinLabel: String,
    val skinMinimal: String,
    val skinClassic: String,

    val menuGame: String,
    val menuNewGame: String,
    val menuQuit: String,
    val menuSettings: String,
) {
    fun difficulty(d: Difficulty): String = when (d) {
        Difficulty.Easy -> easyLabel
        Difficulty.Medium -> mediumLabel
        Difficulty.Hard -> hardLabel
    }

    fun theme(m: ThemeMode): String = when (m) {
        ThemeMode.Dark -> themeDark
        ThemeMode.Light -> themeLight
        ThemeMode.System -> themeSystem
    }

    fun skin(s: Skin): String = when (s) {
        Skin.Minimal -> skinMinimal
        Skin.Classic -> skinClassic
    }
}

internal val EnglishStrings = Strings(
    seedLabel = "Seed",
    copySeedButton = "Copy",
    seedCopiedToast = "Seed copied",
    newGameButton = "New Game",
    startButton = "Start",
    stopAndStartButton = "Stop and start a new game",
    difficultyLabel = "Difficulty",
    orPasteSeed = "Or paste a seed",
    seedFormatHint = "Format: <E|M|H>-<hex>. Difficulty comes from the prefix.",
    seedFormatError = "Invalid seed. Expected <E|M|H>-<up to 15 hex digits>.",
    playAgainButton = "Play again",
    gameWonHeadline = "You won",
    gameLostHeadline = "Boom",
    clearedInPrefix = "Cleared in",
    lastedPrefix = "Lasted",
    easyLabel = "Easy",
    mediumLabel = "Medium",
    hardLabel = "Hard",
    gameTab = "Game",
    historyTab = "History",
    settingsTab = "Settings",
    historyHeader = "History",
    historyEmpty = "No games played yet",
    historyClear = "Clear",
    outcomeWon = "WON",
    outcomeLost = "LOST",
    statsHeader = "Stats",
    statsBestTime = "Best",
    statsAverageTime = "Avg",
    statsAverageWinTime = "Avg (wins)",
    statsAverageLossTime = "Avg (losses)",
    statsWinRate = "Win rate",
    statsTotalGames = "Played",
    statsTotalWins = "Won",
    statsTotalLosses = "Lost",
    statsCurrentStreak = "Streak",
    statsLongestStreak = "Best streak",
    statsThreeBV = "3BV",
    statsThreeBVPerSecond = "3BV/s",
    statsAverageThreeBVPerSecond = "Avg 3BV/s",
    statsMedianTime = "Median",
    statsRecentGames = "Recent games",
    statsBack = "Back",
    statsNoData = "—",
    statsWinTimeChartLabel = "Seconds",
    statsChartAllGames = "All games",
    statsChartWinsOnly = "Wins",
    statsChartLossesOnly = "Losses",
    settingsHeader = "Settings",
    languageLabel = "Language",
    themeLabel = "Theme",
    themeDark = "Dark",
    themeLight = "Light",
    themeSystem = "System",
    skinLabel = "Style",
    skinMinimal = "Minimal",
    skinClassic = "Classic",
    menuGame = "Game",
    menuNewGame = "New Game",
    menuQuit = "Quit",
    menuSettings = "Settings",
)

internal val UkrainianStrings = Strings(
    seedLabel = "Сід",
    copySeedButton = "Копіювати",
    seedCopiedToast = "Сід скопійовано",
    newGameButton = "Нова гра",
    startButton = "Старт",
    stopAndStartButton = "Завершити й розпочати нову",
    difficultyLabel = "Складність",
    orPasteSeed = "Або вставте сід",
    seedFormatHint = "Формат: <E|M|H>-<hex>. Складність береться з префікса.",
    seedFormatError = "Невірний сід. Очікується <E|M|H>-<до 15 шістнадцяткових цифр>.",
    playAgainButton = "Зіграти ще раз",
    gameWonHeadline = "Перемога",
    gameLostHeadline = "Бабах",
    clearedInPrefix = "Розчищено за",
    lastedPrefix = "Протривало",
    easyLabel = "Легко",
    mediumLabel = "Середньо",
    hardLabel = "Важко",
    gameTab = "Гра",
    historyTab = "Історія",
    settingsTab = "Налаштування",
    historyHeader = "Історія",
    historyEmpty = "Ще не зіграно жодної гри",
    historyClear = "Очистити",
    outcomeWon = "ПЕРЕМОГА",
    outcomeLost = "ПРОГРАШ",
    statsHeader = "Статистика",
    statsBestTime = "Кращий",
    statsAverageTime = "Серед.",
    statsAverageWinTime = "Серед. (перем.)",
    statsAverageLossTime = "Серед. (прогр.)",
    statsWinRate = "Перемог",
    statsTotalGames = "Зіграно",
    statsTotalWins = "Перемоги",
    statsTotalLosses = "Поразки",
    statsCurrentStreak = "Серія",
    statsLongestStreak = "Кращ. серія",
    statsThreeBV = "3BV",
    statsThreeBVPerSecond = "3BV/с",
    statsAverageThreeBVPerSecond = "Серед. 3BV/с",
    statsMedianTime = "Медіана",
    statsRecentGames = "Останні ігри",
    statsBack = "Назад",
    statsNoData = "—",
    statsWinTimeChartLabel = "Секунди",
    statsChartAllGames = "Усі ігри",
    statsChartWinsOnly = "Перемоги",
    statsChartLossesOnly = "Поразки",
    settingsHeader = "Налаштування",
    languageLabel = "Мова",
    themeLabel = "Тема",
    themeDark = "Темна",
    themeLight = "Світла",
    themeSystem = "Системна",
    skinLabel = "Стиль",
    skinMinimal = "Мінімал",
    skinClassic = "Класика",
    menuGame = "Гра",
    menuNewGame = "Нова гра",
    menuQuit = "Вийти",
    menuSettings = "Налаштування",
)
